---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: cache-restore
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-restore
  environment:
    BUCKET_NAME: prima-ci-cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - git-clone

- name: check-secrets
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - check-secrets-grants
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  depends_on:
  - git-clone

- name: check-public-docker-images
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - check-public-docker-images
  depends_on:
  - git-clone

- name: build-image
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - sed -i 's/USER node/USER root/g' ./Dockerfile
  - docker build -t prima/pyxis-ci:${DRONE_COMMIT} ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - cache-restore

- name: dependencies
  image: prima/pyxis-ci:${DRONE_COMMIT}
  commands:
  - yarn
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - build-image

- name: lint
  image: prima/pyxis-ci:${DRONE_COMMIT}
  commands:
  - yarn lint
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: review
  image: prima/pyxis-ci:${DRONE_COMMIT}
  commands:
  - yarn review:elm
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: test
  image: prima/pyxis-ci:${DRONE_COMMIT}
  commands:
  - yarn test
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - lint
  - review

- name: build
  image: prima/pyxis-ci:${DRONE_COMMIT}
  commands:
  - yarn build
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - test

- name: storybook
  image: prima/pyxis-ci:${DRONE_COMMIT}
  commands:
  - yarn storybook:build
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - build

- name: sassdocs
  image: prima/pyxis-ci:${DRONE_COMMIT}
  commands:
  - yarn sassdocs:build
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - build

- name: cache-save
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-save .cache node_modules
  environment:
    BUCKET_NAME: prima-ci-cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - master
  depends_on:
  - dependencies
  - lint
  - review
  - test
  - build
  - storybook
  - sassdocs

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint

trigger:
  event:
  - push

---
kind: pipeline
name: build-staging

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: cache-restore
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-restore
  environment:
    BUCKET_NAME: prima-ci-cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - git-clone

- name: build-image
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - sed -i 's/USER node/USER root/g' ./Dockerfile
  - docker build -t prima/pyxis-ci:${DRONE_COMMIT} ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - cache-restore

- name: build-staging
  image: prima/pyxis-ci:${DRONE_COMMIT}
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - ./deploy/build staging
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  depends_on:
  - build-image

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint

trigger:
  branch:
  - master
  event:
  - push
  status:
  - success

depends_on:
- default

---
kind: pipeline
name: deploy-it-staging

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: pre-start
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - pre-start-scripts
  depends_on:
  - git-clone

- name: deploy
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - ./deploy/deploy-it staging
  environment:
    CLOUDFLARE_TOKEN:
      from_secret: cloudflare_token
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  depends_on:
  - pre-start

- name: captainhook-notification
  image: public.ecr.aws/prima/drone-webhook
  settings:
    signature-secret:
      from_secret: captainhook_secret
    urls: http://captainhook-internal.prima.it/drone/deploy?rollback=${ROLLBACK}
  depends_on:
  - deploy

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint

trigger:
  branch:
  - master
  event:
  - push
  status:
  - success

depends_on:
- build-staging

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: public.ecr.aws/prima/drone-email
  settings:
    from: drone@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

trigger:
  status:
  - failure
  target:
    exclude:
    - qa-stack
    - qa-it
    - qa

depends_on:
- default
- build-staging
- deploy-it-staging

---
kind: signature
hmac: 9d05a8107d6ad8b75d94ab5f9b9975e842a3a0bc09d2e726d85adc11e3f83a69

...
