name: Feature request
description: Suggest an idea, improvement or anything can help making Pyxis a better product.
title: "[Feature]: "
labels: ["feature-request", "triage"]
body:
  - type: dropdown
    id: pyxis_module
    attributes:
      label: Pyxis module
      multiple: true
      options:
        - SCSS
        - React
        - Elm
        - Icons
        - Tokens
    validations:
      required: true
  - type: textarea
    id: feature_description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I would like to...
    validations:
      required: true
  - type: textarea
    id: feature_suggested_solution
    attributes:
      label: Suggested solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: feature_alternative_solution
    attributes:
      label: Alternative solution
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: dropdown
    id: feature_priority
    attributes:
      label: Priority
      description: How much is this feature critical for your development or business?
      multiple: true
      options:
        - Show stopper
        - Critical
        - Major
        - Minor
    validations:
      required: true
